# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Anthropic Studios

# Use for SEO
tagline: "An independent game company."
description: "An independent game company."
author: AnthropicSt # default twitter handle attribution, can be changed per-post
twitter:
  username: AnthropicSt
  card: summary_large_image
facebook:
  publisher: https://www.facebook.com/AnthropicStudios/
logo: /assets/logo.png
social:
  links:
    - https://twitter.com/anthropicst
    - https://www.instagram.com/anthropicstudios/
    - https://www.facebook.com/AnthropicStudios/
    - https://store.steampowered.com/app/1110620/Way_of_Rhea/

email: anthropicstudios@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.anthropicstudios.com" # the base hostname & protocol for your site, e.g. http://example.com
enforce_ssl: "www.anthropicstudios.com"
twitter_username: AnthropicSt
facebook_username: AnthropicStudios
# github_username: MasonRemaley # None of my cool stuff is public yet so no reason to link people here
instagram_username: AnthropicStudios
show_excerpts: true
permalink: /:year/:month/:day/:title/

header_pages:
  - blog.md
  - press.md
  - contact.md

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
minima:
  skin: dark
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

keep_files: [CNAME, .git]
